### ISSUE TITLE
Footer erstreckt sich über die gesamte Seitenbreite

### ISSUE THREAD

**Issue by fnogatz** [koenige/modules-clubs#4]
Das HTML-Element `#foot` erstreckt sich unsichtbar über die gesamte Seitenbreite, damit sind alle Elemente unterhalb des 78 Pixel großen Balkens nicht anwählbar. Der Unterschied ist hier im Beispiel gut zu erkennen:

https://user-images.githubusercontent.com/881988/118132893-7c19d700-b400-11eb-8a79-f9bba2319f4d.mp4

**Comment by koenige** [comment]
Danke! [layout: fix footer width so that it does not unnecessarily overlay map ](https://github.com/koenige/modules-clubs/commit/1652bb4dc3c4ea6d684ae6b1b5a5f32b3eefb423)
